Add LSM6DS driver
DotBots/DotBot-firmware pull request #201
Opened 2023-04-28 15:01 UTC by malishav

2023-05-03 07:59 UTC, aabadie requested changes
Some comments, mostly cleanup so rather minor

2023-05-03 07:59 UTC, aabadie commented on drv/lsm6ds/lsm6ds.c
> +static const gpio_t sda     = { .port = 0, .pin = 11 };
```suggestion
static const gpio_t scl     = { .port = DB_I2C_SCL_PORT, .pin = DB_I2C_SCL_PIN };
static const gpio_t sda     = { .port = DB_I2C_SDA_PORT, .pin = DB_I2C_SDA_PIN };
```
(and run make format to align with the line below)

2023-05-03 07:59 UTC, aabadie commented on drv/lsm6ds/lsm6ds.c
> +static const gpio_t imu_int = { .port = 0, .pin = 20 };
For compatibility between boards, add a define in the corresponding board config headers. That will avoid pin clash and the driver could also be tested on DK boards.

2023-05-03 07:59 UTC, aabadie commented on drv/lsm6ds/lsm6ds.c
> +}
Missing newline at end of files it seems.

2023-05-03 08:31 UTC, malishav commented on drv/lsm6ds.h
> +int8_t lsm6ds_last_roll(void);
fixed

2023-05-03 09:08 UTC, malishav commented on drv/lsm6ds/lsm6ds.c
> +static const gpio_t sda     = { .port = 0, .pin = 11 };
fixed

2023-05-03 09:09 UTC, malishav commented on projects/01drv_lsm6ds/01drv_lsm6ds.c
> +//=========================== functions =========================================
fixed

2023-05-03 13:21 UTC, aabadie reviewed
One minor remaining nit pick and after that it's good to go

2023-05-04 07:57 UTC, malishav commented on drv/lsm6ds.h
> + * @param[in] scl       callback pointer invoked whenever data is ready
fixed

2023-05-04 15:37 UTC, aabadie approved these changes

2023-05-04 15:38 UTC, merged