183 add support for the mini mote 2
DotBots/DotBot-firmware pull request #316
Opened 2024-05-30 14:28 UTC by SaidAlvarado

2024-05-31 09:43 UTC, aabadie requested changes
Looks overall. I think the test application should be removed as it's just a copy-paste. You also have to modify the `Makefile` similar to dotbot/sailbot-v1 as there are limitation with the nrf52833 MCU.
Another thing that would be nice is to add the lh2_mini_mote in the target list in the GitHub action file (in .github/workflows/build/yml). Watch out, you have to manually add a download step in the release job.

2024-05-31 09:43 UTC, aabadie commented on projects/03app_lh2_mini_mote_test/03app_lh2_mini_mote_test.c
> + * TODO: currently it's a copy of the LH2_mini_mote App
Can we just remove that file to avoid unnecessary code duplication? It will be relatively easy to add a proper test application later.

2024-06-03 15:11 UTC, SaidAlvarado commented on projects/03app_lh2_mini_mote_test/03app_lh2_mini_mote_test.c
> + * TODO: currently it's a copy of the LH2_mini_mote App
I implemented the test app.
And added the requested changes to the Makefiles and the github workflow (I think, not 100% sure I did correctly)

2024-06-04 07:28 UTC, aabadie commented on projects/03app_lh2_mini_mote_test/03app_lh2_mini_mote_test.c
> +            ;
```suggestion
        while (db_timer_hf_now(0) < busy_loop) {}
```

2024-06-04 07:35 UTC, aabadie commented on projects/03app_lh2_mini_mote_test/03app_lh2_mini_mote_test.c
> +        // busy loop - hf_delay_us hangs if I use it here
If I get it right, you want the RGB LED to be refreshed every 100us following the orientation of the board. Instead of busy looping here, would it make sense to trigger a callback that sets a boolean. Refresh the LED in the main loop when the boolean is true.
It's also interesting that for very short delays the timer hangs. Is 100us a hard requirement? Can it be a little relaxed somehow to somethings longer, like 1ms or even 10ms?

2024-06-04 14:46 UTC, SaidAlvarado commented on projects/03app_lh2_mini_mote_test/03app_lh2_mini_mote_test.c
> +        // busy loop - hf_delay_us hangs if I use it here
thanks for catching that, it was supposed to be 100ms.
For some reason the HF timer doesn't play nice with DEBUG mode. I have the feeling that it keeps going, even if you pause the program. But it works fine in actual operation.
I removed the busy loop and now use a timer_hf interruption + flag to do this.

2024-06-04 14:47 UTC, SaidAlvarado commented
I'm going to be honest, I have no idea why the CI is failing, specially the doc.

2024-06-05 07:20 UTC, aabadie commented
> I have no idea why the CI is failing, specially the doc.

The CI is now passing. There were 3 problems with the doc (fixed in ed7ea3d742dfc0a256822905c5d58420a6e3b021):
- The doxygen group of the lh2 minimote application was duplicated and thus Doxygen was failing (this one was the error in CI, others came after it was fixed)
- The new applications were not added to the Sphinx toctree
- The new applications didn't contain any README and this is required by Sphinx

I also fixed the Makefile so the right applications are built for the minimote. Also the minimote application is checked by the CI on nrf52833dk, nrf52840dk and nrf5340dk-app because they provide the required pin configurations.

Finally there was a misuse the timer API (did you try to build locally before pushing?), fixed in c33a2218925d98c081de86b2eb57a80dbb7925bc.

I also allowed my self to rebase on top the latest main branch because there was a merge commit of the main branch in the history. This was a pain to do. While I was at it, I reworded the commit comments (dropped all references to #183 and use lower case).

Can you double check that everything is working because it was a tough rebase, I hope nothing got lost in the process.

2024-06-05 09:58 UTC, aabadie commented
Please don't use git merge or a bare git pull ! It creates a merge commit like be8ba2b518b80cdddbfa8fcb94dc9f07cda2cfa9. It took me an hour to cleanup the history of that PR....

2024-06-05 10:15 UTC, SaidAlvarado commented
Thanks for your help with this.
I verified that the project works as expected. 👍

And indeed I found a bug with the ISM330 driver.
I'm addressing it with #321.

2024-06-05 10:20 UTC, aabadie approved these changes

2024-06-05 10:21 UTC, merged